language: php

os:
    - linux

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3

before_script:
    - php --version
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - composer check
    - composer generate-reports

after_script:
    - bash <(curl -s https://codecov.io/bash) -f "build/phpunit/coverage/clover/index.xml"
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/phpunit/coverage/clover/index.xml
