language: php

os:
    - linux

matrix:
    allow_failures:
        - php: hhvm

    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3

before_script:
    - php --version
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpunit --coverage-clover=coverage.xml --debug
    - php vendor/bin/phpunit --configuration ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;

after_script:
    - bash <(curl -s https://codecov.io/bash)
